### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [riccardoklinger/batch-vector-layer-saver#2]
The functionality described in the About seems already present in core QGIS.
Please clarify what the plugin is actually adding.
Sorry for bothering, but we are trying hard not to duplicate functionality, so to reduce confusion for the users and administrative burden.
Thanks.

**Comment by riccardoklinger** [comment]
at my knowledge, there is no build-in functionality to batch export your project layers at once in different formats. If there is one, I would love to use this one...

**Comment by pcav** [comment]
Right, no direct export from Processing. I would think adding it there would be appropriate.
Thanks.

**Comment by riccardoklinger** [comment]
I'll close this now. please reopen @pcav if needed.
